# Generated by Django 4.2.7 on 2024-01-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=20000)),
                ('short_url', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
